data:
  data: cyp1a2_veith_train1_pos
  dir: './data'

ckpt: cyp1a2_veith_train1_pos

sampler:
  predictor: Reverse
  corrector: Langevin
  snr: 0.2
  scale_eps: 0.9
  n_steps: 1

sample:
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 42