data:
  data: cyp2c19_veith_40_train1_neg
  dir: './data'

ckpt: Aug30-04:37:17_700

sampler:
  predictor: Reverse
  corrector: Langevin
  snr: 0.2
  scale_eps: 0.95
  n_steps: 1

sample:
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 42