data:
  data: bbb_martins_33_train1_neg
  dir: './data'

ckpt: Aug21-21:28:16_900

sampler:
  predictor: Reverse
  corrector: Langevin
  snr: 0.2
  scale_eps: 0.99
  n_steps: 1

sample:
  use_ema: False
  noise_removal: True
  probability_flow: False
  eps: 1.0e-4
  seed: 42